export const CREATE_USER_REQUEST="CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS="CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL="CREATE_USER_FAIL";

export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";

export const LOGOUT="LOGOUT";

export const CREATE_STORE_REQUEST="CREATE_STORE_REQUEST";
export const CREATE_STORE_SUCCESS="CREATE_STORE_SUCCESS";
export const CREATE_STORE_FAIL="CREATE_STORE_FAIL";

export const LOAD_STORE_REQUEST="LOAD_STORE_REQUEST";
export const LOAD_STORE_SUCCESS="LOAD_STORE_SUCCESS";
export const LOAD_STORE_FAIL="LOAD_STORE_FAIL";